import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  yes: {
    width: 100,
    backgroundColor: "black",
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
  },
  no: {
    width: 100,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
  },
  text: {
    color: "white",
    marginBottom: 20,
    fontSize: 15,
  },
  title: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  buttonsBox: {
    display: "flex",
    flexDirection: "row",
    gap: 50,
  },
  style: {
    width: "100%",
    height: "100%",
    backgroundColor: "black",
    opacity: 0.4,
    position: "absolute",
    top: 0,
    left: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  logicBox: {
    backgroundColor: "rgb(75 85 99)",
    opacity: 1,
    width: 300,
    height: 150,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    shadowColor: "white",
    shadowOpacity: 0.25,
    shadowRadius: 20,
    gap: 10,
  },
  logoutBox: {
    width: "111%",
    height: "120%",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: "0%",
    left: "0%",
  },
  itemText: {
    fontSize: 19,
    color: "#fff",
  },
  itemTextNo: {
    fontSize: 19,
    color: "black",
  },
  iconContainer: {
    width: 60,
    height: 60,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#262a35",
    borderRadius: 100,
  },
  itemBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  accountItem: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  email: {
    color: "#bdbcbd",
    fontSize: 15,
  },
  username: {
    fontSize: 20,
    color: "#fff",
  },
  textContainer: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  profileContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    borderColor: "#2d3036",
    borderBottomWidth: 2,
    gap: 7,
  },
  profilePic: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  logo: {
    fontSize: 30,
  },
  headerContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  name: {
    color: "#fff",
    fontSize: 27,
    fontWeight: "600",
  },
  container: {
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    paddingVertical: 50,
    paddingHorizontal: 20,
    backgroundColor: "#181a21",
    gap: 20,
  },
});
